title: Path 3 Indian
description: "A Third Way for the Modern Indian"
baseurl: ""
url: "https://path3indian.com"

collections:
  book:
    output: true
    permalink: /book/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
